spring:
    datasource:
      url: jdbc:mysql://localhost:3306/basicdb
      username: root
      password: mysql
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true
      database-platform: org.hibernate.dialect.MySQL5Dialect